Repository InterDigitalInc/AdvantEDGE, pull requests merged in 2019-10, with the labels that each got.

#24 Pod Placement
  charts/meep-virt-engine/virt-templates/values-template.yaml
  examples/demo1/src/demo-server/go/README.md
  examples/demo1/src/iperf-proxy/go/README.md
  go-apps/meep-ctrl-engine/api/swagger.yaml
  go-apps/meep-ctrl-engine/server/README.md
  go-apps/meep-ctrl-engine/server/process.go
  go-apps/meep-loc-serv/server/README.md
  go-apps/meep-metrics-engine/server/README.md
  go-apps/meep-mg-manager/server/README.md
  go-apps/meep-tc-engine/api/swagger.yaml
  go-apps/meep-tc-engine/server/README.md
  go-apps/meep-tc-engine/server/process.go
  go-apps/meep-virt-engine/server/chart_template.go
  go-packages/meep-ctrl-engine-client/api/swagger.yaml
  go-packages/meep-ctrl-engine-client/docs/Process.md
  go-packages/meep-ctrl-engine-client/process.go
  go-packages/meep-ctrl-engine-model/api/swagger.yaml
  go-packages/meep-ctrl-engine-model/docs/Process.md
  go-packages/meep-ctrl-engine-model/process.go
  js-apps/meep-frontend/src/js/containers/cfg/cfg-network-element-container.js
  js-apps/meep-frontend/src/js/meep-constants.js
  js-apps/meep-frontend/src/js/util/elem-utils.js
  js-apps/meep-frontend/src/js/util/scenario-utils.js
  js-packages/meep-ctrl-engine-client/docs/Process.md
  js-packages/meep-ctrl-engine-client/src/model/Process.js
  js-packages/meep-ctrl-engine-client/test/model/Process.spec.js
  test/cypress/integration/tests/scenario-cfg-spec.js
Labels: enhancement

#25 Throughput measurements fix + Demo1 code cleanup
  examples/demo1/README.md
  examples/demo1/demo1-dashboards.json
  examples/demo1/src/demo-frontend/src/css/demo-svc.scss
  examples/demo1/src/demo-frontend/src/index.html
  examples/demo1/src/demo-frontend/src/js/demo-svc.js
  examples/demo2/README.md
  go-apps/meep-tc-sidecar/destination.go
Labels: bug

#23 Bandwidth Sharing (Tier 1)
  go-apps/meep-tc-engine/go.mod
  go-apps/meep-tc-engine/go.sum
  go-apps/meep-tc-engine/server/db.go
  go-apps/meep-tc-engine/server/tc-engine.go
  go-apps/meep-tc-sidecar/db.go
  go-apps/meep-tc-sidecar/destination.go
  go-apps/meep-tc-sidecar/go.mod
  go-apps/meep-tc-sidecar/go.sum
  go-apps/meep-tc-sidecar/main.go
  go-packages/meep-bw-sharing/bwsharing.go
  go-packages/meep-bw-sharing/const.go
  go-packages/meep-bw-sharing/defaultBandwidthSharing.go
  go-packages/meep-bw-sharing/go.mod
  go-packages/meep-bw-sharing/go.sum
  go-packages/meep-bw-sharing/newbandwidthSharing.go.template
  go-packages/meep-redis/db.go
Labels: enhancement

#26 rounding latencies
  go-apps/meep-tc-sidecar/destination.go
Labels: bug

#28 Meepctl kibana configuration fixes
  go-apps/meepctl/utils/kibana.go
Labels: bug

#31 New Exec tab with data analytics dashboard
  js-apps/meep-frontend/src/js/components/helper-components/nc-group.js
  js-apps/meep-frontend/src/js/containers/cfg/cfg-network-element-container.js
  js-apps/meep-frontend/src/js/containers/dashboard-container.js
  js-apps/meep-frontend/src/js/containers/exec/exec-page-container.js
  js-apps/meep-frontend/src/js/containers/exec/mobility-event-pane.js
  js-apps/meep-frontend/src/js/containers/exec/network-characteristics-event-pane.js
  js-apps/meep-frontend/src/js/containers/graph-utils.js
  js-apps/meep-frontend/src/js/containers/idc-apps-view.js
  js-apps/meep-frontend/src/js/containers/idc-line-chart.js
  js-apps/meep-frontend/src/js/containers/idc-node.js
  js-apps/meep-frontend/src/js/containers/meep-container.js
  js-apps/meep-frontend/src/js/containers/meep-drawer.js
  js-apps/meep-frontend/src/js/containers/resizeable-container.js
  js-apps/meep-frontend/src/js/meep-constants.js
  js-apps/meep-frontend/src/js/state/exec/metrics-reducer.js
  js-apps/meep-frontend/src/js/state/ui/index.js
Labels: bug, enhancement

#29 Bandwidth Sharing (Tier 2+)
  go-apps/meep-tc-engine/server/tc-engine.go
  go-apps/meep-tc-sidecar/destination.go
  go-apps/meep-tc-sidecar/main.go
  go-packages/meep-bw-sharing/bwsharing.go
  go-packages/meep-bw-sharing/bwsharing_test.go
  go-packages/meep-bw-sharing/defaultBandwidthSharing.go
  go-packages/meep-bw-sharing/defaultBandwidthSharing_test.go
  go-packages/meep-bw-sharing/newbandwidthSharing.go.template
Labels: enhancement

#30 os.hostname() should not be used in meepctl tool
  go-apps/meepctl/cmd/configKibana.go
  go-apps/meepctl/cmd/dockerize.go
  go-apps/meepctl/utils/kibana.go
Labels: bug

#33 tc-engine and bwsharing concurrent updates
  go-apps/meep-tc-engine/server/tc-engine.go
  go-apps/meep-tc-sidecar/main.go
  go-packages/meep-bw-sharing/defaultBandwidthSharing.go
Labels: bug

#34 Default dashboard state + UI state in local storage
  js-apps/meep-frontend/src/js/containers/cfg/cfg-page-container.js
  js-apps/meep-frontend/src/js/containers/dashboard-container.js
  js-apps/meep-frontend/src/js/containers/exec/event-creation-pane.js
  js-apps/meep-frontend/src/js/containers/exec/exec-page-container.js
  js-apps/meep-frontend/src/js/containers/idc-line-chart-back.js
  js-apps/meep-frontend/src/js/containers/idc-line-chart.js
  js-apps/meep-frontend/src/js/containers/meep-container.js
  js-apps/meep-frontend/src/js/containers/meep-drawer.js
  js-apps/meep-frontend/src/js/containers/settings/settings-page-container.js
  js-apps/meep-frontend/src/js/meep-constants.js
  js-apps/meep-frontend/src/js/meep-controller.js
  js-apps/meep-frontend/src/js/state/ui/index.js
  js-apps/meep-frontend/src/js/util/meep-utils.js
  js-apps/meep-frontend/src/js/util/metrics.js
  js-apps/meep-frontend/src/js/util/persist.js
Labels: enhancement
