Repository InterDigitalInc/AdvantEDGE, pull requests merged in 2019-11, with the labels that each got.

#39 ETSI 013 compliance
  go-apps/meep-loc-serv/server/loc-serv.go
Labels: bug

#40 Frontend fixes for integration to develop branch
  js-apps/meep-frontend/package.json
  js-apps/meep-frontend/src/js/containers/exec/exec-page-container.js
  js-apps/meep-frontend/src/js/containers/meep-container.js
  js-apps/meep-frontend/src/js/containers/settings/settings-page-container.js
  js-apps/meep-frontend/src/js/meep-constants.js
  js-apps/meep-frontend/src/js/util/meep-utils.js
  test/cypress/integration/tests/meep-settings-spec.js
  test/cypress/integration/tests/scenario-exec-spec-mob-event-demo-app.js
  test/package-lock.json
Labels: bug

#43 Net Char Manager support for latency, jitter & packet loss + TC Engine cleanup
  go-apps/meep-mg-manager/server/mg-manager.go
  go-apps/meep-tc-engine/go.mod
  go-apps/meep-tc-engine/tc-engine.go
  go-apps/meep-tc-sidecar/destination.go
  go-apps/meep-tc-sidecar/main.go
  go-packages/meep-model/model.go
  go-packages/meep-model/model_test.go
  go-packages/meep-net-char-mgr/algo-segment.go
  go-packages/meep-net-char-mgr/algo-segment_test.go
  go-packages/meep-net-char-mgr/net-char-mgr.go
  js-apps/meep-frontend/src/js/containers/monitor/monitor-page-container.js
  test/run-ut.sh
Labels: bug, enhancement

#48 Added Notification specs to swagger UI
  .meepctl-repocfg.yaml
  examples/demo1/src/demo-server/go/README.md
  examples/demo1/src/iperf-proxy/go/README.md
  go-apps/meep-ctrl-engine/server/README.md
  go-apps/meep-loc-serv/server/README.md
  go-apps/meep-metrics-engine/server/README.md
  go-apps/meep-mg-manager/server/README.md
  go-apps/meepctl/cmd/build.go
Labels: enhancement

#47 Net Char Manager segment algorithm fix to handle Mobility events
  go-packages/meep-net-char-mgr/algo-segment.go
  go-packages/meep-net-char-mgr/algo-segment_test.go
Labels: bug

#49 Adding influxdb helm chart
  .meepctl-repocfg.yaml
  charts/influxdb/.helmignore
  charts/influxdb/Chart.yaml
  charts/influxdb/README.md
  charts/influxdb/templates/NOTES.txt
  charts/influxdb/templates/_helpers.tpl
  charts/influxdb/templates/backup-cronjob.yaml
  charts/influxdb/templates/config.yaml
  charts/influxdb/templates/ingress.yaml
  charts/influxdb/templates/init-config.yaml
  charts/influxdb/templates/persistentvolume.yaml
  charts/influxdb/templates/persistentvolumeclaim.yaml
  charts/influxdb/templates/post-install-set-auth.yaml
  charts/influxdb/templates/secret.yaml
  charts/influxdb/templates/service.yaml
  charts/influxdb/templates/statefulset.yaml
  charts/influxdb/templates/storageclass.yaml
  charts/influxdb/values.yaml
  go-apps/meepctl/cmd/delete.go
  go-apps/meepctl/cmd/deploy.go
  go-apps/meepctl/cmd/version.go
  test/setup-ut-env.sh
Labels: enhancement

#51 Metric Store with InfluxDB
  charts/influxdb/values.yaml
  go-apps/meep-ctrl-engine/go.mod
  go-apps/meep-ctrl-engine/go.sum
  go-apps/meep-ctrl-engine/server/ctrl-engine.go
  go-apps/meep-ctrl-engine/server/ctrl-engine_test.go
  go-apps/meep-tc-sidecar/destination.go
  go-apps/meep-tc-sidecar/go.mod
  go-apps/meep-tc-sidecar/go.sum
  go-apps/meep-tc-sidecar/main.go
  go-apps/meep-webhook/webhook.go
  go-packages/meep-metric-store/convert.go
  go-packages/meep-metric-store/events.go
  go-packages/meep-metric-store/events_test.go
  go-packages/meep-metric-store/go.mod
  go-packages/meep-metric-store/go.sum
  go-packages/meep-metric-store/metric-store.go
  go-packages/meep-metric-store/metric-store_test.go
  go-packages/meep-metric-store/network.go
  go-packages/meep-metric-store/network_test.go
  test/run-ut.sh
  test/setup-ut-env.sh
Labels: enhancement
