Repository InterDigitalInc/AdvantEDGE, pull requests merged in 2020-09, with the labels that each got.

#122 Retention of Manual Event Creation fields on changing tabs
  js-apps/meep-frontend/src/js/containers/exec/event-creation-pane.js
  js-apps/meep-frontend/src/js/containers/exec/exec-page-container.js
  js-apps/meep-frontend/src/js/containers/exec/mobility-event-pane.js
  js-apps/meep-frontend/src/js/containers/exec/network-characteristics-event-pane.js
  js-apps/meep-frontend/src/js/state/ui/index.js
  js-apps/meep-frontend/webpack.config.js
Labels: bug

#126 Supporting K8s 1.19 in current setup
  charts/couchdb/templates/_helpers.tpl
  charts/couchdb/templates/statefulset.yaml
  charts/kube-state-metrics/templates/deployment.yaml
  charts/redis/templates/metrics-deployment.yaml
  charts/redis/templates/redis-master-statefulset.yaml
  charts/redis/templates/redis-slave-deployment.yaml
  js-apps/meep-frontend/src/js/components/helper-components/cancel-apply-pair.js
  js-apps/meep-frontend/src/js/containers/exec/event-creation-pane.js
  js-apps/meep-frontend/src/js/containers/exec/mobility-event-pane.js
  js-apps/meep-frontend/src/js/containers/exec/network-characteristics-event-pane.js
  test/cypress/integration/tests/scenario-exec-spec-mob-event-demo-app.js
  test/cypress/integration/tests/scenario-exec-spec.js
Labels: enhancement

#128 Fixed Net Char Event displays values without selecting an element
  js-apps/meep-frontend/package.json
  js-apps/meep-frontend/src/js/containers/exec/event-creation-pane.js
  js-apps/meep-frontend/src/js/containers/exec/network-characteristics-event-pane.js
  js-apps/meep-frontend/src/js/state/exec/selected-scenario-element.js
Labels: bug

#132 user-chart folder creation and demo2 documentation update
  examples/demo2/README.md
  examples/demo2/build-demo2.sh
  go-apps/meepctl/cmd/deploy.go
Labels: bug

#131 Disconnected Physical Locations + Configurable POA Selection Priority
  .meepctl-repocfg.yaml
  examples/demo1/src/demo-server/go/README.md
  examples/demo1/src/iperf-proxy/go/README.md
  go-apps/meep-gis-engine/server/README.md
  go-apps/meep-gis-engine/server/gis-engine.go
  go-apps/meep-loc-serv/sbi/loc-serv-sbi.go
  go-apps/meep-loc-serv/server/README.md
  go-apps/meep-metrics-engine/server/v2/README.md
  go-apps/meep-mg-manager/server/README.md
  go-apps/meep-mon-engine/server/README.md
  go-apps/meep-platform-ctrl/api/swagger.yaml
  go-apps/meep-platform-ctrl/server/README.md
  go-apps/meep-rnis/sbi/rnis-sbi.go
  go-apps/meep-rnis/server/README.md
  go-apps/meep-sandbox-ctrl/api/swagger.yaml
  go-apps/meep-sandbox-ctrl/server/README.md
  go-apps/meepctl/cmd/version.go
  go-apps/meepctl/utils/config.go
  go-packages/meep-data-model/api/swagger.yaml
  go-packages/meep-data-model/docs/EventMobility.md
  go-packages/meep-data-model/docs/PhysicalLocation.md
  go-packages/meep-data-model/model_event_mobility.go
  go-packages/meep-data-model/model_physical_location.go
  go-packages/meep-model/model.go
  go-packages/meep-model/model_test.go
  go-packages/meep-model/validator.go
  go-packages/meep-net-char-mgr/algo-segment.go
  go-packages/meep-net-char-mgr/algo-segment_test.go
  go-packages/meep-postgis/db.go
  go-packages/meep-postgis/db_test.go
  go-packages/meep-sandbox-ctrl-client/api/swagger.yaml
  go-packages/meep-sandbox-ctrl-client/docs/EventMobility.md
  go-packages/meep-sandbox-ctrl-client/docs/PhysicalLocation.md
  go-packages/meep-sandbox-ctrl-client/model_event_mobility.go
  go-packages/meep-sandbox-ctrl-client/model_physical_location.go
  js-apps/meep-frontend/src/js/containers/cfg/cfg-network-element-container.js
  js-apps/meep-frontend/src/js/containers/cfg/cfg-page-container.js
  js-apps/meep-frontend/src/js/containers/exec/mobility-event-pane.js
  js-apps/meep-frontend/src/js/containers/idc-map.js
  js-apps/meep-frontend/src/js/meep-constants.js
  js-apps/meep-frontend/src/js/util/elem-utils.js
  js-apps/meep-frontend/src/js/util/scenario-utils.js
  js-packages/meep-platform-ctrl-client/docs/PhysicalLocation.md
  js-packages/meep-platform-ctrl-client/src/model/PhysicalLocation.js
  js-packages/meep-platform-ctrl-client/test/api/ScenarioConfigurationApi.spec.js
  js-packages/meep-platform-ctrl-client/test/model/PhysicalLocation.spec.js
  js-packages/meep-sandbox-ctrl-client/docs/EventMobility.md
  js-packages/meep-sandbox-ctrl-client/docs/PhysicalLocation.md
  js-packages/meep-sandbox-ctrl-client/src/model/EventMobility.js
  js-packages/meep-sandbox-ctrl-client/src/model/PhysicalLocation.js
  js-packages/meep-sandbox-ctrl-client/test/api/ActiveScenarioApi.spec.js
  js-packages/meep-sandbox-ctrl-client/test/api/EventReplayApi.spec.js
  js-packages/meep-sandbox-ctrl-client/test/api/EventsApi.spec.js
  js-packages/meep-sandbox-ctrl-client/test/model/PhysicalLocation.spec.js
Labels: bug, enhancement

#133 Demo scenario version upgrade to v1.5.3
  examples/demo1/demo1-scenario.yaml
  examples/demo2/demo2-scenario.yaml
Labels: bug

#134 Scenario Import fix + UT fixes
  go-apps/meep-loc-serv/server/loc-serv_test.go
  go-apps/meep-rnis/server/rnis_test.go
  go-packages/meep-postgis/db_test.go
  js-apps/meep-frontend/src/js/util/scenario-utils.js
Labels: bug

#127 Thread safe operations in subscription based services
  go-apps/meep-loc-serv/server/loc-serv.go
  go-apps/meep-rnis/server/rnis.go
Labels: bug

#130 AdvantEDGE services handling of UE movement between different RAT (4G, 5G, Wifi)
  go-apps/meep-rnis/api/swagger.yaml
  go-apps/meep-rnis/sbi/rnis-sbi.go
  go-apps/meep-rnis/server/model_plmn_info.go
  go-apps/meep-rnis/server/rnis.go
  go-apps/meep-rnis/server/rnis_test.go
  go-packages/meep-rnis-client/api/swagger.yaml
  go-packages/meep-rnis-client/docs/PlmnInfo.md
  go-packages/meep-rnis-client/model_plmn_info.go
  js-apps/meep-frontend/src/js/containers/cfg/cfg-network-element-container.js
Labels: enhancement
