Repository InterDigitalInc/AdvantEDGE, pull requests merged in 2020-05, with the labels that each got.

#79 grafana dashboards for meep http log
  charts/grafana/dashboards/http-log-byId.json
  charts/grafana/dashboards/http-loggers.json
  charts/grafana/values.yaml
  js-apps/meep-frontend/src/js/meep-constants.js
  test/cypress/integration/tests/scenario-monitor-spec.js
Labels: enhancement

#80 Added Open Map Tiles (omt) dependency
  .meepctl-repocfg.yaml
  charts/open-map-tiles/.helmignore
  charts/open-map-tiles/Chart.yaml
  charts/open-map-tiles/templates/NOTES.txt
  charts/open-map-tiles/templates/_helpers.tpl
  charts/open-map-tiles/templates/deployment.yaml
  charts/open-map-tiles/templates/ingress.yaml
  charts/open-map-tiles/templates/persistentvolume.yaml
  charts/open-map-tiles/templates/persistentvolumeclaim.yaml
  charts/open-map-tiles/templates/service.yaml
  charts/open-map-tiles/templates/tests/test-connection.yaml
  charts/open-map-tiles/values.yaml
  go-apps/meepctl/cmd/deploy.go
Labels: enhancement

#81 Http-logger not logging in influx
  go-apps/meep-sandbox-ctrl/server/sandbox-ctrl.go
  go-packages/meep-http-logger/httpLogger.go
  js-apps/meep-frontend/src/js/meep-constants.js
Labels: bug

#84 Sandbox Swagger UI
  .meepctl-repocfg.yaml
  charts/meep-loc-serv/templates/deployment.yaml
  charts/meep-loc-serv/values-template.yaml
  charts/meep-metrics-engine/templates/deployment.yaml
  charts/meep-metrics-engine/values-template.yaml
  charts/meep-mg-manager/templates/deployment.yaml
  charts/meep-mg-manager/values-template.yaml
  charts/meep-rnis/templates/deployment.yaml
  charts/meep-rnis/values-template.yaml
  charts/meep-sandbox-ctrl/templates/deployment.yaml
  charts/meep-sandbox-ctrl/values-template.yaml
  charts/meep-tc-engine/templates/deployment.yaml
  charts/meep-tc-engine/values-template.yaml
  charts/meep-virt-engine/templates/deployment.yaml
  charts/meep-virt-engine/values.yaml
  go-apps/meep-loc-serv/server/loc-serv.go
  go-apps/meep-metrics-engine/server/v2/metrics-engine.go
  go-apps/meep-platform-ctrl/Dockerfile
  go-apps/meep-platform-ctrl/server/routers.go
  go-apps/meep-rnis/server/rnis.go
  go-apps/meep-sandbox-ctrl/Dockerfile
  go-apps/meep-sandbox-ctrl/entrypoint.sh
  go-apps/meep-sandbox-ctrl/server/routers.go
  go-apps/meep-virt-engine/server/chart-template.go
  go-apps/meep-virt-engine/server/virt-engine.go
  go-apps/meepctl/cmd/build.go
  go-apps/meepctl/cmd/deploy.go
  go-apps/meepctl/cmd/version.go
  go-apps/meepctl/utils/config.go
Labels: enhancement

#83 RNIS UT testing
  go-apps/meep-loc-serv/sbi/loc-serv-sbi.go
  go-apps/meep-metrics-engine/server/v2/metrics-engine.go
  go-apps/meep-mg-manager/server/mg-manager.go
  go-apps/meep-rnis/go.mod
  go-apps/meep-rnis/go.sum
  go-apps/meep-rnis/sbi/rnis-sbi.go
  go-apps/meep-rnis/server/rnis.go
  go-apps/meep-rnis/server/rnis_test.go
  go-apps/meep-sandbox-ctrl/server/sandbox-ctrl.go
  go-packages/meep-http-logger/httpLogger.go
  go-packages/meep-rnis-client/go.mod
Labels: enhancement

#86 Postgis chart
  .meepctl-repocfg.yaml
  charts/open-map-tiles/templates/deployment.yaml
  charts/open-map-tiles/values.yaml
  charts/postgis/.helmignore
  charts/postgis/Chart.yaml
  charts/postgis/README.md
  charts/postgis/ci/commonAnnotations.yaml
  charts/postgis/ci/default-values.yaml
  charts/postgis/ci/shmvolume-disabled-values.yaml
  charts/postgis/files/README.md
  charts/postgis/files/conf.d/README.md
  charts/postgis/files/docker-entrypoint-initdb.d/README.md
  charts/postgis/templates/NOTES.txt
  charts/postgis/templates/_helpers.tpl
  charts/postgis/templates/configmap.yaml
  charts/postgis/templates/extended-config-configmap.yaml
  charts/postgis/templates/initialization-configmap.yaml
  charts/postgis/templates/metrics-configmap.yaml
  charts/postgis/templates/metrics-svc.yaml
  charts/postgis/templates/networkpolicy.yaml
  charts/postgis/templates/persistentvolume.yaml
  charts/postgis/templates/persistentvolumeclaim.yaml
  charts/postgis/templates/podsecuritypolicy.yaml
  charts/postgis/templates/prometheusrule.yaml
  charts/postgis/templates/role.yaml
  charts/postgis/templates/rolebinding.yaml
  charts/postgis/templates/secrets.yaml
  charts/postgis/templates/serviceaccount.yaml
  charts/postgis/templates/servicemonitor.yaml
  charts/postgis/templates/statefulset-slaves.yaml
  charts/postgis/templates/statefulset.yaml
  charts/postgis/templates/storageclass.yaml
  charts/postgis/templates/svc-headless.yaml
  charts/postgis/templates/svc-read.yaml
  charts/postgis/templates/svc.yaml
  charts/postgis/values.yaml
  go-apps/meepctl/cmd/deploy.go
Labels: enhancement

#87 Pod Status Monitoring
  .meepctl-repocfg.yaml
  charts/meep-mon-engine/templates/deployment.yaml
  charts/meep-mon-engine/values.yaml
  go-apps/meep-mon-engine/go.mod
  go-apps/meep-mon-engine/go.sum
  go-apps/meep-mon-engine/server/mon-engine.go
  go-apps/meep-platform-ctrl/server/platform-ctrl.go
  go-apps/meepctl/cmd/deploy.go
  go-apps/meepctl/cmd/version.go
  go-apps/meepctl/utils/config.go
  js-apps/meep-frontend/src/js/containers/meep-container.js
  js-apps/meep-frontend/src/js/state/exec/state-reducer.js
  test/start-ut-env.sh
Labels: enhancement

#88 Location service UT testing
  go-apps/meep-loc-serv/go.mod
  go-apps/meep-loc-serv/sbi/loc-serv-sbi.go
  go-apps/meep-loc-serv/server/loc-serv.go
  go-apps/meep-loc-serv/server/loc-serv_test.go
  go-apps/meep-rnis/server/rnis.go
  go-apps/meep-rnis/server/rnis_test.go
Labels: enhancement

#89 Virt Engine Helm Concurrency
  .meepctl-repocfg.yaml
  charts/meep-mon-engine/values.yaml
  charts/meep-virt-engine/values.yaml
  go-apps/meep-virt-engine/helm/delete.go
  go-apps/meep-virt-engine/helm/helm.go
  go-apps/meep-virt-engine/helm/install.go
  go-apps/meep-virt-engine/helm/worker.go
  go-apps/meep-virt-engine/server/chart-template.go
  go-apps/meep-virt-engine/server/virt-engine.go
  go-apps/meepctl/cmd/deploy.go
  js-apps/meep-frontend/src/js/containers/exec/exec-page-container.js
Labels: bug, enhancement
