Repository InterDigitalInc/AdvantEDGE, pull requests merged in 2020-06, with the labels that each got.

#91 Dynamic Addition/Removal UE triggers a cell change for RNIS and Location service
  go-apps/meep-loc-serv/sbi/loc-serv-sbi.go
  go-apps/meep-loc-serv/server/loc-serv.go
  go-apps/meep-rnis/sbi/rnis-sbi.go
  go-apps/meep-rnis/server/rnis.go
  go-packages/meep-model/model.go
Labels: bug

#95 Map View in Frontend Exec Dashboard
  examples/demo1/src/demo-server/go/README.md
  examples/demo1/src/iperf-proxy/go/README.md
  go-apps/meep-gis-engine/api/swagger.yaml
  go-apps/meep-gis-engine/server/README.md
  go-apps/meep-gis-engine/server/gis-engine.go
  go-apps/meep-gis-engine/server/model_geo_data_asset.go
  go-apps/meep-loc-serv/server/README.md
  go-apps/meep-metrics-engine/server/v2/README.md
  go-apps/meep-mg-manager/server/README.md
  go-apps/meep-mon-engine/server/README.md
  go-apps/meep-platform-ctrl/server/README.md
  go-apps/meep-rnis/server/README.md
  go-apps/meep-sandbox-ctrl/server/README.md
  js-apps/meep-frontend/package-lock.json
  js-apps/meep-frontend/package.json
  js-apps/meep-frontend/src/js/components/dialogs/id-dialog.js
  js-apps/meep-frontend/src/js/containers/exec/dashboard-container.js
  js-apps/meep-frontend/src/js/containers/idc-map.js
  js-apps/meep-frontend/src/js/containers/meep-container.js
  js-apps/meep-frontend/src/js/meep-constants.js
  js-apps/meep-frontend/src/js/meep-controller.js
  js-apps/meep-frontend/src/js/state/exec/index.js
  js-apps/meep-frontend/src/js/state/exec/map-reducer.js
  js-apps/meep-frontend/src/js/state/ui/index.js
  js-packages/meep-gis-engine-client/docs/AutomationState.md
  js-packages/meep-gis-engine-client/docs/GeoDataAsset.md
  js-packages/meep-gis-engine-client/docs/GeospatialDataApi.md
  js-packages/meep-gis-engine-client/package-lock.json
  js-packages/meep-gis-engine-client/src/api/AutomationApi.js
  js-packages/meep-gis-engine-client/src/api/GeospatialDataApi.js
  js-packages/meep-gis-engine-client/src/model/AutomationState.js
  js-packages/meep-gis-engine-client/src/model/GeoDataAsset.js
  js-packages/meep-gis-engine-client/test/api/AutomationApi.spec.js
  js-packages/meep-gis-engine-client/test/api/GeospatialDataApi.spec.js
  js-packages/meep-gis-engine-client/test/model/GeoDataAsset.spec.js
Labels: enhancement

#100 User specific configuration
  .meepctl-repocfg.yaml
  charts/couchdb/values.yaml
  charts/meep-platform-ctrl/templates/service.yaml
  charts/meep-virt-engine/templates/deployment.yaml
  charts/meep-virt-engine/templates/user-values-pv.yaml
  charts/meep-virt-engine/values.yaml
  charts/open-map-tiles/values.yaml
  charts/redis/values.yaml
  go-apps/meep-virt-engine/server/chart-template.go
  go-apps/meepctl/cmd/deploy.go
Labels: enhancement

#99 Net Char Update Event fixes
  examples/demo1/demo1-scenario.yaml
  examples/demo1/src/demo-server/go/README.md
  examples/demo1/src/iperf-proxy/go/README.md
  examples/demo2/demo2-scenario.yaml
  go-apps/meep-gis-engine/server/README.md
  go-apps/meep-loc-serv/server/README.md
  go-apps/meep-metrics-engine/server/v2/README.md
  go-apps/meep-mg-manager/server/README.md
  go-apps/meep-mon-engine/server/README.md
  go-apps/meep-platform-ctrl/server/README.md
  go-apps/meep-rnis/server/README.md
  go-apps/meep-sandbox-ctrl/api/swagger.yaml
  go-apps/meep-sandbox-ctrl/server/README.md
  go-packages/meep-data-model/api/swagger.yaml
  go-packages/meep-model/model.go
  go-packages/meep-model/model_test.go
  go-packages/meep-model/validator.go
  go-packages/meep-sandbox-ctrl-client/api/swagger.yaml
  js-apps/meep-frontend/package.json
  js-apps/meep-frontend/src/js/components/dialogs/id-dialog.js
  js-apps/meep-frontend/src/js/components/helper-components/nc-group.js
  js-apps/meep-frontend/src/js/containers/cfg/cfg-network-element-container.js
  js-apps/meep-frontend/src/js/containers/exec/network-characteristics-event-pane.js
  js-apps/meep-frontend/src/js/meep-constants.js
  js-apps/meep-frontend/src/js/middlewares/exec-displayed-scenario-middleware.js
  js-packages/meep-sandbox-ctrl-client/docs/EventNetworkCharacteristicsUpdate.md
  js-packages/meep-sandbox-ctrl-client/src/model/EventNetworkCharacteristicsUpdate.js
Labels: bug

#101 Kd sp25 dev ansible
  js-apps/meep-frontend/src/js/containers/idc-map.js
  js-apps/meep-frontend/src/js/util/scenario-utils.js
  playbooks/README.md
  playbooks/ansible.cfg
  playbooks/group_vars/all.yml
  playbooks/hosts.ini
  playbooks/install-runtime-env.yml
  playbooks/roles/docker/files/daemon.json
  playbooks/roles/docker/tasks/install.yml
  playbooks/roles/docker/tasks/main.yml
  playbooks/roles/golang/tasks/install.yml
  playbooks/roles/golang/tasks/main.yml
  playbooks/roles/helm/files/tiller-crb.yaml
  playbooks/roles/helm/tasks/install.yml
  playbooks/roles/helm/tasks/main.yml
  playbooks/roles/helm/tasks/uninstall.yml
  playbooks/roles/kubernetes/common/tasks/install.yml
  playbooks/roles/kubernetes/common/tasks/main.yml
  playbooks/roles/kubernetes/common/tasks/swap.yml
  playbooks/roles/kubernetes/master/files/weave.yml
  playbooks/roles/kubernetes/master/meta/main.yml
  playbooks/roles/kubernetes/master/tasks/cni.yml
  playbooks/roles/kubernetes/master/tasks/init.yml
  playbooks/roles/kubernetes/master/tasks/main.yml
  playbooks/roles/kubernetes/master/tasks/token.yml
  playbooks/roles/kubernetes/worker/handlers/main.yml
  playbooks/roles/kubernetes/worker/meta/main.yml
  playbooks/roles/kubernetes/worker/tasks/join.yml
  playbooks/roles/kubernetes/worker/tasks/main.yml
  playbooks/uninstall-runtime-env.yml
  test/start-ut-env.sh
Labels: bug, enhancement

#102 Doc update for v1.5.0
  CONTRIBUTING.md
  README.md
  docs/cla/interdigital-corporate-cla-v1.pdf
  docs/cla/interdigital-individual-cla-v1.pdf
  docs/meepctl/meepctl.md
  docs/meepctl/meepctl_build.md
  docs/meepctl/meepctl_config.md
  docs/meepctl/meepctl_config_gitdir.md
  docs/meepctl/meepctl_config_ip.md
  docs/meepctl/meepctl_config_ports.md
  docs/meepctl/meepctl_config_registry.md
  docs/meepctl/meepctl_delete.md
  docs/meepctl/meepctl_deploy.md
  docs/meepctl/meepctl_dockerize.md
  docs/meepctl/meepctl_genmd.md
  docs/meepctl/meepctl_lint.md
  docs/meepctl/meepctl_replay.md
  docs/meepctl/meepctl_replay_cat.md
  docs/meepctl/meepctl_replay_export.md
  docs/meepctl/meepctl_replay_generate.md
  docs/meepctl/meepctl_replay_import.md
  docs/meepctl/meepctl_replay_ls.md
  docs/meepctl/meepctl_replay_rm.md
  docs/meepctl/meepctl_replay_start.md
  docs/meepctl/meepctl_replay_status.md
  docs/meepctl/meepctl_replay_stop.md
  docs/meepctl/meepctl_test.md
  docs/meepctl/meepctl_version.md
Labels: documentation
