Repository InterDigitalInc/AdvantEDGE, pull requests merged in 2020-11, with the labels that each got.

#144 Added playbooks for installation of NPM, Node, and GoLang
  playbooks/group_vars/all.yml
  playbooks/hosts.ini
  playbooks/install-development-env.yml
  playbooks/roles/golang/tasks/install.yml
  playbooks/roles/golang/tasks/main.yml
  playbooks/roles/node/files/install_nvm.sh
  playbooks/roles/node/tasks/install.yml
  playbooks/roles/node/tasks/main.yml
Labels: enhancement

#148 OAuth Support
  .meepctl-repocfg.yaml
  charts/meep-gis-engine/values-template.yaml
  charts/meep-loc-serv/values-template.yaml
  charts/meep-metrics-engine/values-template.yaml
  charts/meep-mg-manager/values-template.yaml
  charts/meep-platform-ctrl/values.yaml
  charts/meep-rnis/values-template.yaml
  charts/meep-sandbox-ctrl/values-template.yaml
  charts/meep-virt-engine/values.yaml
  charts/meep-wais/values-template.yaml
  config/permissions.yaml
  examples/demo1/src/demo-server/go/README.md
  examples/demo1/src/iperf-proxy/go/README.md
  go-apps/meep-gis-engine/server/README.md
  go-apps/meep-loc-serv/server/README.md
  go-apps/meep-metrics-engine/server/v2/README.md
  go-apps/meep-mg-manager/server/README.md
  go-apps/meep-mon-engine/server/README.md
  go-apps/meep-platform-ctrl/Dockerfile
  go-apps/meep-platform-ctrl/api/swagger.yaml
  go-apps/meep-platform-ctrl/go.mod
  go-apps/meep-platform-ctrl/go.sum
  go-apps/meep-platform-ctrl/server/README.md
  go-apps/meep-platform-ctrl/server/api_user_authentication.go
  go-apps/meep-platform-ctrl/server/platform-ctrl.go
  go-apps/meep-platform-ctrl/server/routers.go
  go-apps/meep-platform-ctrl/server/user_authentication.go
  go-apps/meep-rnis/server/README.md
  go-apps/meep-sandbox-ctrl/entrypoint.sh
  go-apps/meep-sandbox-ctrl/server/README.md
  go-apps/meep-virt-engine/server/chart-template.go
  go-apps/meep-virt-engine/server/virt-engine.go
  go-apps/meep-wais/server/README.md
  go-apps/meep-wais/server/api_default.go
  go-apps/meep-wais/server/routers.go
  go-apps/meepctl/cmd/deploy.go
  go-packages/meep-sessions/session-store.go
  js-packages/meep-platform-ctrl-client/README.md
  js-packages/meep-platform-ctrl-client/docs/UserAuthenticationApi.md
  js-packages/meep-platform-ctrl-client/src/api/UserAuthenticationApi.js
  js-packages/meep-platform-ctrl-client/test/api/UserAuthenticationApi.spec.js
Labels: enhancement

#150 OAuth Improvements
  .meepctl-repocfg.yaml
  go-apps/meep-platform-ctrl/server/platform-ctrl.go
  go-apps/meep-platform-ctrl/server/user_authentication.go
  go-apps/meep-rnis/server/package-lock.json
  go-apps/meep-wais/server/package-lock.json
  go-apps/meepctl/cmd/version.go
  go-apps/meepctl/utils/config.go
  go-packages/meep-sessions/session-store.go
  go-packages/meep-users/db.go
  go-packages/meep-users/db_test.go
  go-packages/meep-wais-client/docs/InlineResponse2004.md
  go-packages/meep-wais-client/docs/Measurement.md
  go-packages/meep-wais-client/docs/MeasurementConfig.md
  go-packages/meep-wais-client/docs/MeasurementLinkList.md
Labels: bug, enhancement

#153 Swagger UI yaml reference fix + WAIS codegen fixes + version bump
  .meepctl-repocfg.yaml
  go-apps/meep-loc-serv/server/README.md
  go-apps/meep-loc-serv/server/logger.go
  go-apps/meep-loc-serv/server/model_connection_type.go
  go-apps/meep-loc-serv/server/model_operation_status.go
  go-apps/meep-loc-serv/server/model_user_event_type.go
  go-apps/meep-loc-serv/server/routers.go
  go-apps/meep-rnis/server/README.md
  go-apps/meep-sandbox-ctrl/entrypoint.sh
  go-apps/meep-wais/server/README.md
  go-apps/meep-wais/server/api_wai.go
  go-apps/meep-wais/server/logger.go
  go-apps/meep-wais/server/routers.go
  go-apps/meepctl/cmd/build.go
  go-apps/meepctl/cmd/deploy.go
  go-apps/meepctl/cmd/version.go
  go-apps/meepctl/utils/config.go
  js-apps/meep-swagger-ui/index.html
Labels: bug

#154 SubscriptionLinkList matching specs
  go-apps/meep-wais/api/swagger.yaml
  go-apps/meep-wais/server/README.md
  go-apps/meep-wais/server/model_subscription_link_list.go
  go-apps/meep-wais/server/model_subscription_link_list__links.go
  go-apps/meep-wais/server/wais.go
  go-apps/meep-wais/server/wais_test.go
  go-packages/meep-wais-client/README.md
  go-packages/meep-wais-client/api/swagger.yaml
  go-packages/meep-wais-client/docs/SubscriptionLinkList.md
  go-packages/meep-wais-client/docs/SubscriptionLinkListLinks.md
  go-packages/meep-wais-client/model_subscription_link_list.go
  go-packages/meep-wais-client/model_subscription_link_list__links.go
Labels: bug

#155 Demo1 supporting v2 location service api and rnis ut fix
  examples/demo1/src/demo-server/api/swagger.yaml
  examples/demo1/src/demo-server/go/localDB.go
  examples/demo1/src/demo-server/go/model_inline_zonal_presence_notification.go
  examples/demo1/src/demo-server/go/model_time_stamp.go
  examples/demo1/src/demo-server/go/model_tracking_notification.go
  examples/demo1/src/demo-server/go/model_user_tracking_notification.go
  examples/demo1/src/demo-server/main.go
  go-apps/meep-rnis/server/rnis_test.go
Labels: bug

#156 Configurable GitHub & GitLab OAuth providers + Session Metrics
  .meepctl-repocfg.yaml
  charts/meep-platform-ctrl/values.yaml
  go-apps/meep-platform-ctrl/go.mod
  go-apps/meep-platform-ctrl/go.sum
  go-apps/meep-platform-ctrl/server/platform-ctrl.go
  go-apps/meep-platform-ctrl/server/user_authentication.go
  go-apps/meepctl/cmd/deploy.go
  go-apps/meepctl/cmd/version.go
  go-apps/meepctl/utils/config.go
  go-packages/meep-metric-store/events_test.go
  go-packages/meep-metric-store/metric-store.go
  go-packages/meep-metric-store/session.go
  go-packages/meep-metric-store/session_test.go
Labels: enhancement

#158 RNIS cell change on 4G POA only
  go-apps/meep-rnis/sbi/rnis-sbi.go
Labels: bug

#161 location API resourceURL fix, WAIS Ap_info, Sta_info returning [], Edge node mobility support
  go-apps/meep-loc-serv/server/loc-serv.go
  go-apps/meep-loc-serv/server/loc-serv_test.go
  go-apps/meep-wais/server/wais.go
  go-packages/meep-model/model.go
  go-packages/meep-model/model_test.go
Labels: bug
