Repository InterDigitalInc/AdvantEDGE, pull requests merged in 2021-12, with the labels that each got.

#330 App Instance ID in Frontend
  go-packages/meep-gc/gc.go
  js-apps/meep-frontend/src/js/containers/exec/exec-table.js
  js-apps/meep-frontend/src/js/containers/meep-container.js
Labels: enhancement

#331 Application Mobility Service refactoring
  go-apps/meep-ams/api/swagger.yaml
  go-apps/meep-ams/go.mod
  go-apps/meep-ams/sbi/ams-sbi.go
  go-apps/meep-ams/server/ams.go
  go-apps/meep-ams/server/convert.go
  go-apps/meep-app-enablement/server/service-mgmt/service-mgmt.go
  go-apps/meep-sandbox-ctrl/server/app-ctrl.go
  go-packages/meep-ams-client/api/swagger.yaml
  js-apps/meep-frontend/src/js/containers/idc-map.js
  test/cypress/integration/tests/scenario-exec-spec.js
Labels: bug, enhancement

#332 Application Mobility Service fixes
  go-apps/meep-ams/server/ams.go
  go-apps/meep-ams/server/convert.go
  go-apps/meep-app-enablement/server/app-support/app-support.go
  go-apps/meep-webhook/go.mod
  go-apps/meep-webhook/go.sum
  go-apps/meep-webhook/main.go
  go-apps/meep-webhook/webhook.go
  js-apps/meep-frontend/src/js/containers/meep-container.js
Labels: bug, enhancement

#335 App Enablement fixes
  go-apps/meep-ams/server/convert.go
  go-apps/meep-app-enablement/server/service-mgmt/service-mgmt.go
Labels: bug

#336 Demo3 Minor Fix
  examples/demo3/README.md
  examples/demo3/demo3-scenario.yaml
  examples/demo3/src/backend/server/demo3_service.go
Labels: bug

#337 Demo3 duplicate tracked devices fix
  examples/demo3/src/backend/server/demo3_service.go
Labels: bug

#338 Release v1.8.1 Documentation
  _config.yml
  assets/images/new-wiki-sitemap.jpg
  docs/overview/edge-services/overview-ams.md
  docs/overview/edge-services/overview-app-enablement-service.md
  docs/overview/edge-services/overview-wais.md
  docs/overview/features/overview-features.md
  docs/overview/features/overview-sandboxes.md
  docs/platform-mgmt/mgmt-cheat-sheet.md
  docs/platform-mgmt/mgmt-workflow.md
  docs/project/project-faq.md
  docs/project/project-roadmap.md
  docs/project/project-sitemap.md
  docs/setup/env-runtime.md
  docs/usage/usage-demo3.md
  docs/usage/usage-execution-view.md
  index.md
Labels: documentation

#341 Demo Scenario fixes
  config/permissions-open.yaml
  examples/demo1/demo1-scenario.yaml
  examples/demo2/demo2-scenario.yaml
Labels: bug
