Repository InterDigitalInc/AdvantEDGE, pull requests merged in 2021-06, with the labels that each got.

#253 Codecoverage enabled for core and sandbox pods
  .meepctl-repocfg.yaml
  charts/meep-gis-engine/templates/codecov-pv.yaml
  charts/meep-gis-engine/values-template.yaml
  charts/meep-loc-serv/templates/codecov-pv.yaml
  charts/meep-loc-serv/values-template.yaml
  charts/meep-metrics-engine/templates/codecov-pv.yaml
  charts/meep-metrics-engine/values-template.yaml
  charts/meep-mg-manager/templates/codecov-pv.yaml
  charts/meep-mg-manager/values-template.yaml
  charts/meep-mon-engine/templates/codecov-pv.yaml
  charts/meep-mon-engine/values.yaml
  charts/meep-rnis/templates/codecov-pv.yaml
  charts/meep-rnis/values-template.yaml
  charts/meep-sandbox-ctrl/templates/codecov-pv.yaml
  charts/meep-sandbox-ctrl/values-template.yaml
  charts/meep-tc-engine/templates/codecov-pv.yaml
  charts/meep-tc-engine/values-template.yaml
  charts/meep-virt-engine/templates/codecov-pv.yaml
  charts/meep-virt-engine/values.yaml
  charts/meep-wais/templates/codecov-pv.yaml
  charts/meep-wais/values-template.yaml
  go-apps/meep-rnis/main_test.go
  go-apps/meep-virt-engine/helm/install.go
  go-apps/meep-wais/main_test.go
  go-apps/meepctl/cmd/deploy.go
Labels: bug, enhancement

#247 Power signal updates on active scenario updates
  go-apps/meep-rnis/sbi/rnis-sbi.go
  go-apps/meep-rnis/server/rnis.go
  go-packages/meep-gis-asset-mgr/asset-mgr.go
Labels: bug

#250 Signals and Distance Influx storage
  .meepctl-repocfg.yaml
  charts/grafana/dashboards/wireless-metrics-aggregation.json
  charts/grafana/dashboards/wireless-metrics-point-to-point.json
  go-apps/meep-gis-engine/server/gis-engine.go
  go-apps/meep-sandbox-ctrl/server/sandbox-ctrl.go
  go-packages/meep-gis-cache/convert.go
  go-packages/meep-gis-cache/gis-cache.go
  go-packages/meep-metrics/events.go
  go-packages/meep-metrics/gis.go
  go-packages/meep-metrics/metric-store.go
  js-apps/meep-frontend/src/js/containers/exec/dashboard-cfg-detail-pane.js
  js-apps/meep-frontend/src/js/containers/exec/dashboard-cfg-pane.js
  js-apps/meep-frontend/src/js/containers/exec/dashboard-container.js
  js-apps/meep-frontend/src/js/containers/exec/event-container.js
  js-apps/meep-frontend/src/js/containers/exec/exec-page-container.js
  js-apps/meep-frontend/src/js/meep-constants.js
  js-apps/meep-frontend/src/js/state/ui/index.js
  js-apps/meep-frontend/src/js/util/scenario-utils.js
Labels: enhancement

#264 RNIS: Mandatory parameters for subscription enforced
  go-apps/meep-rnis/server/rnis.go
Labels: bug

#262 Location service : Area circle and Distance subscription added, Distance endpoint added
  go-apps/meep-gis-engine/server/gis-engine.go
  go-apps/meep-loc-serv/api/swagger.yaml
  go-apps/meep-loc-serv/go.mod
  go-apps/meep-loc-serv/go.sum
  go-apps/meep-loc-serv/server/README.md
  go-apps/meep-loc-serv/server/api_location.go
  go-apps/meep-loc-serv/server/convert.go
  go-apps/meep-loc-serv/server/loc-serv.go
  go-apps/meep-loc-serv/server/loc-serv_test.go
  go-packages/meep-loc-serv-client/README.md
  go-packages/meep-loc-serv-client/api/swagger.yaml
  go-packages/meep-loc-serv-client/api_location.go
  go-packages/meep-loc-serv-client/api_unsupported.go
  go-packages/meep-loc-serv-client/docs/LocationApi.md
  go-packages/meep-loc-serv-client/docs/UnsupportedApi.md
  go-packages/meep-metrics/events_test.go
  test/system/loc-serv_test.go
Labels: enhancement

#263 WAIS (MEC028): Periodic and Trigger combinations for AssocSta and StaDataRate notifications
  go-apps/meep-wais/server/wais.go
  go-apps/meep-wais/server/wais_test.go
  go-packages/meep-wais-client/model_all_of_notification_event.go
  go-packages/meep-wais-client/model_inline_subscription.go
  test/system/rnis_test.go
  test/system/wais_test.go
Labels: enhancement

#267 InfluxDB Backup & Retention
  .meepctl-repocfg.yaml
  charts/influxdb/templates/backup-cronjob.yaml
  charts/influxdb/templates/backup-retention-cronjob.yaml
  charts/influxdb/values.yaml
  config/configure-objstore-secrets.sh
  config/long-term-storage-repocfg.yaml
  config/objstore-influx.cfg
  config/objstore-thanos-archive.yaml
  config/objstore-thanos.yaml
  go-apps/meepctl/cmd/deploy.go
  go-apps/meepctl/cmd/version.go
  go-apps/meepctl/utils/config.go
Labels: enhancement

#268 Long-term Storage configuration updates
  .meepctl-repocfg.yaml
  config/long-term-storage-repocfg.yaml
Labels: enhancement

#270 New feature: MEC013 (Location) periodic subscription
  go-apps/meep-loc-serv/api/swagger.yaml
  go-apps/meep-loc-serv/server/README.md
  go-apps/meep-loc-serv/server/api_location.go
  go-apps/meep-loc-serv/server/convert.go
  go-apps/meep-loc-serv/server/loc-serv.go
  go-apps/meep-loc-serv/server/loc-serv_test.go
  go-packages/meep-loc-serv-client/README.md
  go-packages/meep-loc-serv-client/api/swagger.yaml
  go-packages/meep-loc-serv-client/api_location.go
  go-packages/meep-loc-serv-client/client.go
  go-packages/meep-loc-serv-client/docs/LocationApi.md
  test/system/loc-serv_test.go
Labels: enhancement
