Repository InterDigitalInc/AdvantEDGE, pull requests merged in 2021-03, with the labels that each got.

#214 Modified couchdb authentication process
  charts/couchdb/values.yaml
  go-packages/meep-couch/db.go
Labels: bug

#213 Virt Engine process lifecycle support
  go-apps/meep-loc-serv/server/loc-serv_test.go
  go-apps/meep-rnis/server/rnis_test.go
  go-apps/meep-sandbox-ctrl/server/sandbox-ctrl.go
  go-apps/meep-virt-engine/server/chart-template.go
  go-apps/meep-virt-engine/server/virt-engine.go
  go-apps/meep-wais/server/wais_test.go
  go-packages/meep-model/model.go
  go-packages/meep-model/model_test.go
  go-packages/meep-model/validator.go
  go-packages/meep-net-char-mgr/algo-segment_test.go
Labels: enhancement

#220 App Lifecycle: TC Engine & TC Sidecar support
  .meepctl-repocfg.yaml
  charts/kube-prometheus-stack/values.yaml
  go-apps/meep-mg-manager/main.go
  go-apps/meep-mg-manager/server/mg-manager.go
  go-apps/meep-tc-engine/ip-mgr.go
  go-apps/meep-tc-engine/routing-engine.go
  go-apps/meep-tc-engine/tc-engine.go
  go-apps/meep-tc-sidecar/main.go
  go-apps/meepctl/cmd/version.go
  go-apps/meepctl/utils/config.go
Labels: bug, enhancement

#221 Added prometheus alerts and slack configuration in separate config file.
  charts/kube-prometheus-stack/templates/prometheus/additionalPrometheusRules.yaml
  charts/kube-prometheus-stack/templates/prometheus/prometheus.yaml
  charts/kube-prometheus-stack/templates/prometheus/psp-clusterrole.yaml
  charts/kube-prometheus-stack/templates/prometheus/pvc-deleter.yaml
  charts/kube-prometheus-stack/templates/prometheus/service.yaml
  charts/kube-prometheus-stack/templates/prometheus/serviceThanosSIdecar.yaml
  charts/kube-prometheus-stack/values.yaml
Labels: enhancement

#223 Prometheus Chart fixes + Increased PV size & retention period
  charts/kube-prometheus-stack/templates/prometheus/pvc-deleter.yaml
  charts/kube-prometheus-stack/values.yaml
Labels: bug, enhancement

#222 App Lifecycle: MG Manager support
  go-apps/meep-mg-manager/server/mg-manager.go
  go-apps/meep-sandbox-ctrl/server/sandbox-ctrl.go
  go-apps/meep-tc-engine/routing-engine.go
  go-apps/meep-tc-engine/tc-engine.go
  go-apps/meep-tc-sidecar/destination.go
  go-apps/meep-tc-sidecar/main.go
  go-packages/meep-model/model.go
Labels: bug, enhancement
