Repository InterDigitalInc/AdvantEDGE, pull requests merged in 2021-02, with the labels that each got.

#194 Upgraded kube-state-metrics chart
  charts/kube-state-metrics/Chart.yaml
  charts/kube-state-metrics/README.md
  charts/kube-state-metrics/templates/NOTES.txt
  charts/kube-state-metrics/templates/_helpers.tpl
  charts/kube-state-metrics/templates/clusterrole.yaml
  charts/kube-state-metrics/templates/clusterrolebinding.yaml
  charts/kube-state-metrics/templates/deployment.yaml
  charts/kube-state-metrics/templates/kubeconfig-secret.yaml
  charts/kube-state-metrics/templates/pdb.yaml
  charts/kube-state-metrics/templates/podsecuritypolicy.yaml
  charts/kube-state-metrics/templates/psp-clusterrole.yaml
  charts/kube-state-metrics/templates/psp-clusterrolebinding.yaml
  charts/kube-state-metrics/templates/role.yaml
  charts/kube-state-metrics/templates/rolebinding.yaml
  charts/kube-state-metrics/templates/service.yaml
  charts/kube-state-metrics/templates/serviceMonitor.yaml
  charts/kube-state-metrics/templates/serviceaccount.yaml
  charts/kube-state-metrics/templates/servicemonitor.yaml
  charts/kube-state-metrics/templates/stsdiscovery-role.yaml
  charts/kube-state-metrics/templates/stsdiscovery-rolebinding.yaml
  charts/kube-state-metrics/values.yaml
Labels: enhancement

#196 plugtest and ut small fixes
  go-apps/meep-auth-svc/go.mod
  go-apps/meep-loc-serv/server/loc-serv.go
  go-apps/meep-loc-serv/server/loc-serv_test.go
  go-apps/meep-rnis/server/rnis.go
  go-apps/meep-rnis/server/rnis_test.go
  go-packages/meep-model/model_test.go
  test/system/loc-serv_test.go
  test/system/loopTest.sh
  test/system/rnis_test.go
  test/system/wais_test.go
Labels: bug

#197 Location Service lint fix
  go-apps/meep-loc-serv/server/loc-serv_test.go
Labels: bug

#193 Resolved issues related to pvcs delete and prerequisite crds
  .meepctl-repocfg.yaml
  charts/kube-prometheus-stack/templates/prometheus/pvc-deleter.yaml
  charts/kube-prometheus-stack/templates/prometheus/storageclass.yaml
  charts/kube-prometheus-stack/values.yaml
  go-apps/meepctl/cmd/delete.go
  go-apps/meepctl/cmd/deploy.go
  go-apps/meepctl/cmd/version.go
  go-apps/meepctl/utils/config.go
  go-packages/meep-model/validator.go
Labels: bug, enhancement

#198 Prometheus Scraping of new Auth Service metrics
  .meepctl-repocfg.yaml
  charts/grafana/dashboards/http-log-byId.json
  charts/grafana/dashboards/http-loggers.json
  charts/grafana/dashboards/meep-node-exporter.json
  charts/grafana/values.yaml
  charts/meep-auth-svc/templates/deployment.yaml
  charts/meep-auth-svc/templates/monitor.yaml
  charts/meep-auth-svc/templates/service.yaml
  charts/meep-auth-svc/values.yaml
  charts/nginx-ingress/values.yaml
  go-apps/meep-auth-svc/go.mod
  go-apps/meep-auth-svc/go.sum
  go-apps/meep-auth-svc/main.go
  go-apps/meep-auth-svc/server/auth-svc.go
  go-apps/meep-mon-engine/go.sum
  go-apps/meepctl/cmd/deploy.go
  go-apps/meepctl/cmd/version.go
  go-apps/meepctl/utils/config.go
  go-packages/meep-sessions/session-store.go
Labels: enhancement

#199 Upgraded InfluxDB to 1.8 from 1.7
  charts/influxdb/.helmignore
  charts/influxdb/Chart.yaml
  charts/influxdb/README.md
  charts/influxdb/files/backup-retention-script.sh
  charts/influxdb/templates/NOTES.txt
  charts/influxdb/templates/_helpers.tpl
  charts/influxdb/templates/backup-cronjob.yaml
  charts/influxdb/templates/backup-pvc.yaml
  charts/influxdb/templates/backup-retention-configmap.yaml
  charts/influxdb/templates/backup-retention-cronjob.yaml
  charts/influxdb/templates/config.yaml
  charts/influxdb/templates/configmap.yaml
  charts/influxdb/templates/ingress.yaml
  charts/influxdb/templates/init-config.yaml
  charts/influxdb/templates/meta-configmap.yaml
  charts/influxdb/templates/meta-service.yaml
  charts/influxdb/templates/meta-statefulset.yaml
  charts/influxdb/templates/persistentvolume.yaml
  charts/influxdb/templates/persistentvolumeclaim.yaml
  charts/influxdb/templates/post-install-set-auth.yaml
  charts/influxdb/templates/secret.yaml
  charts/influxdb/templates/service.yaml
  charts/influxdb/templates/serviceaccount.yaml
  charts/influxdb/templates/statefulset.yaml
  charts/influxdb/templates/storageclass.yaml
  charts/influxdb/values.yaml
  go-packages/meep-metric-store/metric-store.go
Labels: enhancement

#200 L2Meas endpoint implementation
  go-apps/meep-auth-svc/go.mod
  go-apps/meep-rnis/sbi/rnis-sbi.go
  go-apps/meep-rnis/server/rnis.go
  go-apps/meep-rnis/server/rnis_test.go
  go-packages/meep-metric-store/network.go
  go-packages/meep-metric-store/network_test.go
Labels: enhancement

#203 mandatory timestamp in userInfo
  go-apps/meep-loc-serv/server/loc-serv.go
  go-apps/meep-loc-serv/server/loc-serv_test.go
Labels: bug

#204 Added Kubernetes dashboards
  charts/grafana/dashboards/k8s-resources-cluster.json
  charts/grafana/dashboards/k8s-resources-namespace.json
  charts/grafana/dashboards/kubelet.json
  charts/grafana/dashboards/prometheus.json
  charts/grafana/values.yaml
Labels: enhancement

#201 Added code for process lifecycle frontend changes
  charts/grafana/dashboards/k8s-resources-cluster.json
  charts/grafana/dashboards/k8s-resources-namespace.json
  charts/grafana/dashboards/kubelet.json
  charts/grafana/dashboards/prometheus.json
  js-apps/meep-frontend/src/js/containers/cfg/cfg-network-element-container.js
  js-apps/meep-frontend/src/js/containers/cfg/cfg-page-container.js
  js-apps/meep-frontend/src/js/containers/exec/event-creation-pane.js
  js-apps/meep-frontend/src/js/containers/exec/exec-page-container.js
  js-apps/meep-frontend/src/js/containers/exec/scenario-update-event-pane.js
  js-apps/meep-frontend/src/js/meep-constants.js
  js-apps/meep-frontend/src/js/state/exec/element-configuration.js
  js-apps/meep-frontend/src/js/state/exec/index.js
  js-apps/meep-frontend/src/js/state/ui/index.js
  js-apps/meep-frontend/src/js/util/scenario-utils.js
Labels: enhancement

#210 Packet loss supporting up to 6 decimals and Terminal network characteristics event fix
  go-apps/meep-tc-engine/tc-engine.go
  go-apps/meep-tc-sidecar/main.go
  js-apps/meep-frontend/src/js/containers/exec/network-characteristics-event-pane.js
Labels: bug

#209 Configurable periodicity in RNIS for MeasRepUe and NrMeasRepUe notifications
  charts/meep-rnis/values-template.yaml
  go-apps/meep-rnis/server/rnis.go
Labels: enhancement

#211 Process Lifecycle API & meep-model updates
  .meepctl-repocfg.yaml
  examples/demo1/demo1-scenario.yaml
  examples/demo1/src/demo-server/go/README.md
  examples/demo1/src/iperf-proxy/go/README.md
  examples/demo2/demo2-scenario.yaml
  go-apps/meep-auth-svc/go.sum
  go-apps/meep-auth-svc/server/README.md
  go-apps/meep-gis-engine/go.sum
  go-apps/meep-gis-engine/server/README.md
  go-apps/meep-loc-serv/go.sum
  go-apps/meep-loc-serv/server/README.md
  go-apps/meep-metrics-engine/go.sum
  go-apps/meep-metrics-engine/server/v2/README.md
  go-apps/meep-mg-manager/go.sum
  go-apps/meep-mg-manager/server/README.md
  go-apps/meep-mon-engine/server/README.md
  go-apps/meep-platform-ctrl/go.sum
  go-apps/meep-platform-ctrl/server/README.md
  go-apps/meep-rnis/go.sum
  go-apps/meep-rnis/server/README.md
  go-apps/meep-sandbox-ctrl/api/swagger.yaml
  go-apps/meep-sandbox-ctrl/go.sum
  go-apps/meep-sandbox-ctrl/server/README.md
  go-apps/meep-sandbox-ctrl/server/sandbox-ctrl.go
  go-apps/meep-tc-engine/go.sum
  go-apps/meep-virt-engine/go.sum
  go-apps/meep-wais/go.sum
  go-apps/meep-wais/server/README.md
  go-packages/meep-data-model/api/swagger.yaml
  go-packages/meep-data-model/docs/NodeDataUnion.md
  go-packages/meep-data-model/model_event_scenario_update.go
  go-packages/meep-data-model/model_node_data_union.go
  go-packages/meep-metrics/network.go
  go-packages/meep-model/go.mod
  go-packages/meep-model/go.sum
  go-packages/meep-model/model.go
  go-packages/meep-model/model_test.go
  go-packages/meep-model/validator.go
  go-packages/meep-model/validator_test.go
  go-packages/meep-net-char-mgr/go.sum
  go-packages/meep-sandbox-ctrl-client/api/swagger.yaml
  go-packages/meep-sandbox-ctrl-client/docs/NodeDataUnion.md
  go-packages/meep-sandbox-ctrl-client/model_event_scenario_update.go
  go-packages/meep-sandbox-ctrl-client/model_node_data_union.go
  js-packages/meep-sandbox-ctrl-client/docs/NodeDataUnion.md
  js-packages/meep-sandbox-ctrl-client/docs/ScenarioNode.md
  js-packages/meep-sandbox-ctrl-client/src/model/EventScenarioUpdate.js
  js-packages/meep-sandbox-ctrl-client/src/model/NodeDataUnion.js
  js-packages/meep-sandbox-ctrl-client/src/model/ScenarioNode.js
  js-packages/meep-sandbox-ctrl-client/test/api/EventReplayApi.spec.js
  js-packages/meep-sandbox-ctrl-client/test/api/EventsApi.spec.js
  js-packages/meep-sandbox-ctrl-client/test/model/NodeDataUnion.spec.js
Labels: enhancement

#212 Changed default timeout to 365 days from 10 min with persistent cookie
  charts/couchdb/values.yaml
Labels: bug
