Repository InterDigitalInc/AdvantEDGE, pull requests merged in 2021-07, with the labels that each got.

#271 AppSupport application termination subscription support
  go-apps/meep-app-enablement/server/app-info/app-info.go
  go-apps/meep-app-enablement/server/app-support/api_app_subscriptions.go
  go-apps/meep-app-enablement/server/app-support/app-support.go
  go-apps/meep-app-enablement/server/app-support/convert.go
  go-apps/meep-app-enablement/server/service-mgmt/service-mgmt.go
Labels: enhancement

#272 MEC013 (distance, areaCircle) - MEC012 - MEC028 phase 1 testing fixes
  go-apps/meep-loc-serv/server/loc-serv.go
  go-apps/meep-wais/sbi/wais-sbi.go
Labels: bug

#273 MEC011 Service Management API subscriptions
  go-apps/meep-app-enablement/server/app-support/app-support.go
  go-apps/meep-app-enablement/server/routers.go
  go-apps/meep-app-enablement/server/service-mgmt/api_app_subscriptions.go
  go-apps/meep-app-enablement/server/service-mgmt/convert.go
  go-apps/meep-app-enablement/server/service-mgmt/model_ser_availability_notification_subscription.go
  go-apps/meep-app-enablement/server/service-mgmt/service-mgmt.go
Labels: enhancement

#274 MEC011 registration of all current platform services
  go-apps/meep-app-enablement/server/service-mgmt/model_one_of_transport_info_endpoint.go
  go-apps/meep-app-enablement/server/service-mgmt/service-mgmt.go
  go-apps/meep-loc-serv/go.mod
  go-apps/meep-loc-serv/go.sum
  go-apps/meep-loc-serv/server/loc-serv.go
  go-apps/meep-rnis/go.mod
  go-apps/meep-rnis/go.sum
  go-apps/meep-rnis/server/rnis.go
  go-apps/meep-wais/go.mod
  go-apps/meep-wais/go.sum
  go-apps/meep-wais/server/wais.go
  go-packages/meep-app-info-client/go.mod
  go-packages/meep-app-support-client/go.mod
  go-packages/meep-service-mgmt-client/go.mod
  go-packages/meep-service-mgmt-client/model_one_of_transport_info_endpoint.go
Labels: enhancement

#275 Mec012-013-028 testing updates
  examples/demo1/src/demo-server/go/README.md
  examples/demo1/src/iperf-proxy/go/README.md
  go-apps/meep-app-enablement/server/app-info/README.md
  go-apps/meep-app-enablement/server/app-support/README.md
  go-apps/meep-app-enablement/server/service-mgmt/README.md
  go-apps/meep-auth-svc/server/README.md
  go-apps/meep-gis-engine/server/README.md
  go-apps/meep-loc-serv/server/README.md
  go-apps/meep-metrics-engine/server/v2/README.md
  go-apps/meep-mg-manager/server/README.md
  go-apps/meep-mon-engine/server/README.md
  go-apps/meep-platform-ctrl/server/README.md
  go-apps/meep-rnis/server/README.md
  go-apps/meep-rnis/server/rnis.go
  go-apps/meep-sandbox-ctrl/server/README.md
  go-apps/meep-wais/api/swagger.yaml
  go-apps/meep-wais/server/README.md
  go-apps/meep-wais/server/model_assoc_sta_subscription_notification_event.go
  go-apps/meep-wais/server/model_sta_data_rate_subscription_notification_event.go
  go-apps/meep-wais/server/wais.go
  go-apps/meep-wais/server/wais_test.go
  go-packages/meep-gis-asset-mgr/asset-mgr.go
  go-packages/meep-wais-client/api/swagger.yaml
  go-packages/meep-wais-client/docs/AssocStaSubscriptionNotificationEvent.md
  go-packages/meep-wais-client/docs/StaDataRateSubscriptionNotificationEvent.md
  go-packages/meep-wais-client/model_all_of_notification_event.go
  go-packages/meep-wais-client/model_assoc_sta_subscription_notification_event.go
  go-packages/meep-wais-client/model_sta_data_rate_subscription_notification_event.go
  test/system/loc-serv_test.go
  test/system/loopTest.sh
  test/system/rnis_test.go
  test/system/wais_test.go
Labels: bug

#278 UE Measurement Notification fixes
  go-apps/meep-rnis/sbi/rnis-sbi.go
  go-apps/meep-rnis/server/rnis.go
Labels: bug

#280 MEC 013-012-028 Phase 2 testing fixed
  go-apps/meep-gis-engine/api/swagger.yaml
  go-apps/meep-gis-engine/server/README.md
  go-apps/meep-gis-engine/server/gis-engine.go
  go-apps/meep-gis-engine/server/model_distance.go
  go-apps/meep-gis-engine/server/model_within_range.go
  go-apps/meep-loc-serv/server/README.md
  go-apps/meep-loc-serv/server/loc-serv.go
  go-apps/meep-wais/server/README.md
  go-apps/meep-wais/server/convert.go
  go-apps/meep-wais/server/wais.go
  go-packages/meep-gis-engine-client/api/swagger.yaml
  go-packages/meep-gis-engine-client/docs/Distance.md
  go-packages/meep-gis-engine-client/docs/WithinRange.md
  go-packages/meep-gis-engine-client/model_distance.go
  go-packages/meep-gis-engine-client/model_within_range.go
  js-packages/meep-gis-engine-client/docs/Distance.md
  js-packages/meep-gis-engine-client/docs/WithinRange.md
  js-packages/meep-gis-engine-client/src/model/Distance.js
  js-packages/meep-gis-engine-client/src/model/WithinRange.js
  js-packages/meep-gis-engine-client/test/api/GeospatialDataApi.spec.js
  js-packages/meep-gis-engine-client/test/model/Distance.spec.js
  js-packages/meep-gis-engine-client/test/model/WithinRange.spec.js
Labels: bug

#282 MEC012-013-028 fixes from testing
  go-apps/meep-loc-serv/server/loc-serv.go
  go-apps/meep-wais/server/wais.go
Labels: bug

#279 MEC011 - Notification hooks
  examples/demo1/src/demo-server/go/README.md
  examples/demo1/src/iperf-proxy/go/README.md
  go-apps/meep-app-enablement/api/app-support/swagger.yaml
  go-apps/meep-app-enablement/api/service-mgmt/swagger.yaml
  go-apps/meep-app-enablement/server/app-info/README.md
  go-apps/meep-app-enablement/server/app-info/app-info.go
  go-apps/meep-app-enablement/server/app-support/README.md
  go-apps/meep-app-enablement/server/app-support/api_timing.go
  go-apps/meep-app-enablement/server/app-support/app-support.go
  go-apps/meep-app-enablement/server/app-support/model_app_termination_notification_subscription.go
  go-apps/meep-app-enablement/server/service-mgmt/README.md
  go-apps/meep-app-enablement/server/service-mgmt/model_ser_availability_notification_subscription.go
  go-apps/meep-app-enablement/server/service-mgmt/service-mgmt.go
  go-apps/meep-auth-svc/server/README.md
  go-apps/meep-loc-serv/go.mod
  go-apps/meep-loc-serv/main.go
  go-apps/meep-loc-serv/server/loc-serv.go
  go-apps/meep-metrics-engine/server/v2/README.md
  go-apps/meep-mg-manager/server/README.md
  go-apps/meep-mon-engine/server/README.md
  go-apps/meep-platform-ctrl/server/README.md
  go-apps/meep-rnis/go.mod
  go-apps/meep-rnis/main.go
  go-apps/meep-rnis/server/README.md
  go-apps/meep-rnis/server/rnis.go
  go-apps/meep-sandbox-ctrl/server/README.md
  go-apps/meep-wais/go.mod
  go-apps/meep-wais/main.go
  go-apps/meep-wais/sbi/wais-sbi.go
  go-apps/meep-wais/server/wais.go
  go-apps/meep-wais/server/wais_test.go
  go-packages/meep-app-support-client/api/swagger.yaml
  go-packages/meep-app-support-client/api_app_confirm_ready.go
  go-packages/meep-app-support-client/api_app_confirm_termination.go
  go-packages/meep-app-support-client/docs/AppConfirmReadyApi.md
  go-packages/meep-app-support-client/docs/AppConfirmTerminationApi.md
  go-packages/meep-app-support-client/docs/AppTerminationNotificationSubscription.md
  go-packages/meep-app-support-client/model_app_termination_notification_subscription.go
  go-packages/meep-service-mgmt-client/api/swagger.yaml
  go-packages/meep-service-mgmt-client/docs/SerAvailabilityNotificationSubscription.md
  go-packages/meep-service-mgmt-client/model_ser_availability_notification_subscription.go
Labels: enhancement

#276 MEP Support
  charts/meep-app-enablement/templates/clusterrolebinding.yaml
  charts/meep-app-enablement/templates/deployment.yaml
  charts/meep-app-enablement/templates/ingress.yaml
  charts/meep-app-enablement/templates/service.yaml
  charts/meep-app-enablement/templates/serviceaccount.yaml
  charts/meep-app-enablement/values-template.yaml
  charts/meep-loc-serv/templates/clusterrolebinding.yaml
  charts/meep-loc-serv/templates/deployment.yaml
  charts/meep-loc-serv/templates/ingress.yaml
  charts/meep-loc-serv/templates/serviceaccount.yaml
  charts/meep-loc-serv/values-template.yaml
  charts/meep-rnis/templates/clusterrolebinding.yaml
  charts/meep-rnis/templates/deployment.yaml
  charts/meep-rnis/templates/ingress.yaml
  charts/meep-rnis/templates/service.yaml
  charts/meep-rnis/templates/serviceaccount.yaml
  charts/meep-rnis/values-template.yaml
  charts/meep-wais/templates/clusterrolebinding.yaml
  charts/meep-wais/templates/deployment.yaml
  charts/meep-wais/templates/ingress.yaml
  charts/meep-wais/templates/service.yaml
  charts/meep-wais/templates/serviceaccount.yaml
  charts/meep-wais/values-template.yaml
  go-apps/meep-app-enablement/server/app-enablement.go
  go-apps/meep-app-enablement/server/app-info/app-info.go
  go-apps/meep-app-enablement/server/app-support/app-support.go
  go-apps/meep-app-enablement/server/service-mgmt/service-mgmt.go
  go-apps/meep-loc-serv/sbi/loc-serv-sbi.go
  go-apps/meep-loc-serv/server/loc-serv.go
  go-apps/meep-mg-manager/server/mg-manager.go
  go-apps/meep-rnis/server/rnis.go
  go-apps/meep-virt-engine/server/chart-template.go
  go-apps/meep-virt-engine/server/virt-engine.go
  go-apps/meep-wais/server/wais.go
  go-apps/meep-webhook/webhook.go
  go-packages/meep-model/model.go
  go-packages/meep-model/model_test.go
  go-packages/meep-net-char-mgr/algo-segment.go
Labels: enhancement

#283 Multi-MEP Support
  go-apps/meep-app-enablement/go.mod
  go-apps/meep-app-enablement/go.sum
  go-apps/meep-app-enablement/server/app-enablement.go
  go-apps/meep-app-enablement/server/app-info/app-info.go
  go-apps/meep-app-enablement/server/app-support/app-support.go
  go-apps/meep-app-enablement/server/service-mgmt/service-mgmt.go
  go-apps/meep-loc-serv/server/loc-serv.go
  go-apps/meep-rnis/sbi/rnis-sbi.go
  go-apps/meep-rnis/server/rnis.go
  go-apps/meep-wais/sbi/wais-sbi.go
  go-apps/meep-wais/server/wais.go
  go-packages/meep-mq/mq.go
  test/system/wais_test.go
Labels: bug, enhancement
