Repository InterDigitalInc/AdvantEDGE, pull requests merged in 2022-12, with the labels that each got.

#410 Meepctl Deploy: Fixed permission error when deleting codecov/bak
  go-apps/meepctl/cmd/deploy.go
Labels: bug

#411 Updated Aggregated Codecov reports script
  go-apps/meepctl/cmd/test.go
Labels: bug

#415 metrics API fix + code regeneration + frontend UE marker fix
  examples/demo1/src/demo-server/go/README.md
  examples/demo1/src/iperf-proxy/go/README.md
  examples/demo3/src/backend/server/README.md
  go-apps/meep-ams/server/README.md
  go-apps/meep-app-enablement/server/app-support/README.md
  go-apps/meep-app-enablement/server/service-mgmt/README.md
  go-apps/meep-auth-svc/server/README.md
  go-apps/meep-gis-engine/server/README.md
  go-apps/meep-loc-serv/server/README.md
  go-apps/meep-metrics-engine/api/v2/swagger.yaml
  go-apps/meep-metrics-engine/server/v2/README.md
  go-apps/meep-metrics-engine/server/v2/metrics-engine.go
  go-apps/meep-metrics-engine/server/v2/model_http_metric.go
  go-apps/meep-metrics-engine/server/v2/model_http_query_params.go
  go-apps/meep-mg-manager/server/README.md
  go-apps/meep-mon-engine/server/README.md
  go-apps/meep-platform-ctrl/server/README.md
  go-apps/meep-rnis/server/README.md
  go-apps/meep-sandbox-ctrl/server/README.md
  go-apps/meep-vis/server/README.md
  go-apps/meep-wais/server/README.md
  go-packages/meep-ams-client/api_amsi.go
  go-packages/meep-ams-client/api_unsupported.go
  go-packages/meep-app-support-client/api_mec_app_support.go
  go-packages/meep-app-support-client/api_unsupported.go
  go-packages/meep-gis-engine-client/api_automation.go
  go-packages/meep-gis-engine-client/api_geospatial_data.go
  go-packages/meep-loc-serv-client/api_location.go
  go-packages/meep-metrics-engine-notification-client/api_notifications.go
  go-packages/meep-metrics/http.go
  go-packages/meep-mg-app-client/api_state_transfer.go
  go-packages/meep-mg-manager-client/api_membership.go
  go-packages/meep-mg-manager-client/api_state_transfer.go
  go-packages/meep-platform-ctrl-client/api_sandbox_control.go
  go-packages/meep-platform-ctrl-client/api_scenario_configuration.go
  go-packages/meep-rnis-client/api_rni.go
  go-packages/meep-sandbox-ctrl-client/api_active_scenario.go
  go-packages/meep-sandbox-ctrl-client/api_applications.go
  go-packages/meep-sandbox-ctrl-client/api_connectivity.go
  go-packages/meep-sandbox-ctrl-client/api_event_replay.go
  go-packages/meep-sandbox-ctrl-client/api_events.go
  go-packages/meep-service-mgmt-client/api_mec_service_mgmt.go
  go-packages/meep-vis-client/api_unsupported.go
  go-packages/meep-vis-client/api_v2xi.go
  go-packages/meep-wais-client/api_unsupported.go
  go-packages/meep-wais-client/api_wai.go
  js-apps/meep-frontend/src/js/containers/idc-map.js
  js-packages/meep-metrics-engine-client/docs/HttpMetric.md
  js-packages/meep-metrics-engine-client/docs/HttpQueryParams.md
  js-packages/meep-metrics-engine-client/package-lock.json
  js-packages/meep-metrics-engine-client/src/model/HttpMetric.js
  js-packages/meep-metrics-engine-client/src/model/HttpQueryParams.js
  js-packages/meep-metrics-engine-client/test/api/MetricsApi.spec.js
  js-packages/meep-metrics-engine-client/test/model/HttpMetric.spec.js
Labels: bug

#416 Metrics Package UT fixes
  go-packages/meep-metrics/http_test.go
  go-packages/meep-metrics/metric-store.go
  go-packages/meep-metrics/metric-store_test.go
Labels: bug

#414 Doc updates
  _config.yml
  assets/images/D2DAutomationConnected.png
  assets/images/D2DAutomationDisconnected.png
  assets/images/D2DExecuteScenario.png
  assets/images/D2DScenarioConfig.png
  docs/overview/edge-services/overview-vis.md
  docs/overview/features/overview-features.md
  docs/overview/features/overview-gis.md
  docs/overview/overview-api.md
  docs/overview/overview-architecture.md
  docs/platform-mgmt/mgmt-workflow.md
  docs/project/project-roadmap.md
  docs/setup/env-runtime.md
  docs/usage/usage-configuration-view.md
  docs/usage/usage-execution-view.md
Labels: documentation

#417 K8s 1.26 Validation
  README.md
  charts/meep-webhook/templates/deployment.yaml
  js-apps/meep-frontend/src/js/components/footer.js
Labels: bug, enhancement

#418 README updates for v1.9.0 release
  README.md
Labels: enhancement

#420 v1.9.0 documentation updates
  _config.yml
  assets/images/new-wiki-sitemap.jpg
  docs/overview/edge-services/overview-ams.md
  docs/overview/edge-services/overview-app-enablement-service.md
  docs/overview/edge-services/overview-edge-services.md
  docs/overview/edge-services/overview-location-service.md
  docs/overview/edge-services/overview-rnis.md
  docs/overview/edge-services/overview-vis.md
  docs/overview/features/overview-d2d.md
  docs/overview/features/overview-features.md
  docs/overview/features/overview-gis.md
  docs/overview/overview-architecture.md
  docs/project/project-roadmap.md
  docs/setup/env-ansible.md
  docs/setup/env-dev.md
  docs/setup/env-runtime.md
  docs/usage/usage-configuration-view.md
  docs/usage/usage-execution-view.md
  index.md
  setup/weave-daemonset-k8s.yaml
Labels: documentation

#421 AdvantEDGE v1.9.0 documentation updates
  _config.yml
  assets/images/D2DAutomationConnected.png
  assets/images/D2DAutomationDisconnected.png
  assets/images/D2DExecuteScenario.png
  assets/images/D2DScenarioConfig.png
  assets/images/architecture.png
  assets/images/new-wiki-sitemap.jpg
  docs/overview/edge-services/overview-ams.md
  docs/overview/edge-services/overview-app-enablement-service.md
  docs/overview/edge-services/overview-edge-services.md
  docs/overview/edge-services/overview-location-service.md
  docs/overview/edge-services/overview-rnis.md
  docs/overview/edge-services/overview-vis.md
  docs/overview/features/overview-d2d.md
  docs/overview/features/overview-features.md
  docs/overview/features/overview-monitoring.md
  docs/overview/overview-api.md
  docs/overview/overview-architecture.md
  docs/platform-mgmt/mgmt-workflow.md
  docs/project/project-faq.md
  docs/project/project-roadmap.md
  docs/setup/env-ansible.md
  docs/setup/env-dev.md
  docs/setup/env-runtime.md
  docs/usage/usage-configuration-view.md
  docs/usage/usage-execution-view.md
  index.md
  setup/weave-daemonset-k8s.yaml
Labels: documentation
